In [1]:
import numpy as np
n1 = np.array([10,20,30,40]) # single dimensional array
n1
type(n1)

numpy.ndarray

In [2]:
n2 = np.array([[1,2,3,4,5],[6,7,8,9,0]]) # multidimensional
n2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [3]:
import numpy as np
n1 = np.zeros((1,2)) # initializing numpy with zeroes
n1
type(n1)

numpy.ndarray

In [4]:
n2 = np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
import numpy as np
n1 = np.full((2,2),10) # initializing numpy array with same number
n1

array([[10, 10],
       [10, 10]])

In [6]:
n1 = np.arange(1,10) # initializing numpy array with range
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
n1 = np.arange(1,20,5) # initializing numpy array with range
n1

array([ 1,  6, 11, 16])

In [9]:
n1 = np.arange(1,20,5) # initializing numpy array with range
n1

array([ 1,  6, 11, 16])

In [18]:
n1 = np.random.randint(1,20,5) # initializing numpy array with random numbers
n1

array([19,  9,  5, 10,  6])

In [38]:
n1 = np.array([[1,2,3],[4,5,6]]) # checking the shape of numpy arrays
n1.shape, n1

((2, 3),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [40]:
n1.shape = (3,2)
n1.shape, n1

((3, 2),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [42]:
# joining numpy arrays
import numpy as np
n1 = np.array([10,20,30]) 
n2 = np.array([40, 50, 60])
np.vstack((n1, n2)) # vertical stack

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
n1 = np.array([10,20,30])
n2 = np.array([40, 50, 60])
np.hstack((n1, n2)) # horizontal stack

array([10, 20, 30, 40, 50, 60])

In [46]:
n1 = np.array([10,20,30])
n2 = np.array([40, 50, 60])
np.column_stack((n1, n2)) # column stack

array([[10, 40],
       [20, 50],
       [30, 60]])

In [3]:
# numpy intersection & difference
import numpy as np
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([5,6,7,8,9,10])
np.intersect1d(n1,n2) # intersecction

array([5, 6])

In [9]:
import numpy as np
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([5,6,7,8,9,10])
np.setdiff1d(n1,n2) # phele k wo element jo n2 me nhi h

array([1, 2, 3, 4])

In [13]:
import numpy as np
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([5,6,7,8,9,10])
np.setdiff1d(n2,n1) # n2 k wo element jo n1 me nhi hai

array([ 7,  8,  9, 10])

In [29]:
# numpy array mathmatics, # addition of numpy arrays
import numpy as np
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.sum([n1,n2]) 
np.sum([n1,n2],axis=0) # column wise addition 
np.sum([n1,n2],axis=1) # row wise addition

array([ 6, 15])

In [31]:
import numpy as np
n1 = np.array([1,2,3]) 
n1 = n1 + 1 # base addition
n1

array([2, 3, 4])

In [33]:
import numpy as np
n1 = np.array([1,2,3])
n1 = n1 * 1 # basic multipication
n1

array([1, 2, 3])

In [35]:
import numpy as np
n1 = np.array([1,2,3])
n1 = n1 - 1
n1

array([0, 1, 2])

In [37]:
import numpy as np
n1 = np.array([1,2,3])
n1 = n1 / 2
n1

array([0.5, 1. , 1.5])

In [43]:
n1 = np.array([2,3,4,5,6])
n1 + 5

array([ 7,  8,  9, 10, 11])

In [51]:
# numpy math functions
import numpy as np
n1 = np.array([1,2,3,4,5])
np.mean(n1) # mean
np.std(n1) # standared deviation
np.median(n1) # median

1.4142135623730951

In [59]:
# numpy save & load
import numpy as np
n1 = np.array([1,2,3,4,5])
np.save('save1',n1) # save

In [61]:
# numpy save & load
import numpy as np
n = np.load('save1.npy') #load
n


array([1, 2, 3, 4, 5])